### ISSUE TITLE
Option to force lights to turn on even if one is already turned on

### ISSUE THREAD

**Issue by EdwardPayne** [maros/Zway-MotionTrigger#1]
I have a couple of lights that I want to turn on when motion is detected. I noticed that my system is not always aware of that all lights actually are off. So I would like to have a check box to turn off the Light-is-already-on feature.

**Comment by maros** [comment]
Do you use the switch polling module? Maybe adding frequent (eg. 1-2min) switch polling would solve your issue? If this does not solve your problem I'll have a look into this. Please let me know

**Comment by EdwardPayne** [comment]
No I don't use the Periodical Switch Polling app. It says it's only for US devices and I'm in Sweden and bought my devices locally so I figure I shouldn't need to use that app?

**Comment by maros** [comment]
Z-Wave switches usually report on/off changes via associations. However, there are a couple of cases where this reporting fails:
- some devices, as mentioned in the SwitchPolling docs, don't report states at all (also true for some EU devices - especially some of the cheaper wall plugs)
- some devices are buggy (eg. Philio relay switches report only one channel)
- associations might be misconfigured
- while zway is restarting/down
- occasional communication errors

So, if the device status in zway regularly does not reflect the actual device status you should use the switch polling module.

**Comment by EdwardPayne** [comment]
You are right. One of the devices were missing an association for group 1. I think maybe this will sort the problem. The device is a Fibaro Wall Plug FGWPE-101.

Thank you for you help and great work with the apps! I see you have made many of them!
