### ISSUE TITLE
Problems with v2.2.3

### ISSUE THREAD

**Issue by cpramhofer** [maros/Zway-MotionTrigger#3]
Always getting the Error "something went wrong" in Version 2.2.3
heard from others that they have the same problem!

thanks a lot for your great work!

Thank you for reporting an issue. In order to address the issue you need to supply following information:

Please make sure that all required information is included and that all checkboxes below are ticked before you submit your issue. Thank you!
- [x] Make sure that you followed all installation instructions in the README. If installed via git ensure that the directory is NOT prefixed with 'ZWay-' and that the user running zway can access all files inside the directory.
- [ ] Include log messages generated while running the highest log level. Log level can be set via /opt/z-way-server/config.xml (highest level = 0, file location may be different). Be sure to include enough context: Not only the line showing the error, but also a couple of lines before and after. Log file is usually located at /var/log/z-way-server.log
- [ ] Append the configuration of the module. The configuration can be obtained by opening this URL in your browser http://#IP#:8083/ZAutomation/api/v1/instances/#INSTANCE-ID#
- [ ] If applicable, please also include steps to reproduce.
- [x] Ensure you are running the latest released version. You can check that via the Apps > Local Apps screen in your Z-Wave>Me. (you might need to remove filters). If a red arrow is displayed next to this module, a newer version is available.
- [x] State the Z-Wave>Me version. See Management > Info

V 2.2.3

**Comment by maros** [comment]
Please provide the information requested in the issue template (tick all the boxes and add the required information)

**Comment by maros** [comment]
Closing due to a lack of actionable information. Please re-open if you are able to provide messages from the error log
